### ISSUE TITLE
What is this pattern?

### ISSUE THREAD

**Issue by baseplate-admin** [coreproject-moe/coreproject-seeder#8]
Hi while exploring the codebase i saw this weird class.

https://github.com/coreproject-moe/coreproject-seeder/blob/a537ea15bcddcead9a150491445b43b19b5cfc4e/src/seeder_flet/lib/views/login.py#L3-L57

Could you explain why did we make a class instead of a pure function. 

Thanks UwU

**Comment by moonlitgrace** [comment]
Clases makes it look more complex, more horrible and more graceful.
Then why not use Class-kun

**Comment by baseplate-admin** [comment]
> Then why not use Class-kun

call me old, but i hate doing class when it's not natively supported by a framework
